export const LinkData = [
    {
        id: 'twitter',
        name: 'Twitter Link',
        path: 'https://twitter.com/swift_fingers_/',
        title: '',
        target: '_blank',
    },
    {
        id: 'btn__zuri',
        name: 'Zuri Team',
        path: 'https://training.zuri.team/',
        title: '',
        target: '_blank',
    },
    {
        id: 'books',
        name: 'Zuri Books',
        path: 'https://books.zuri.team/',
        title: "You'll fnd books about coding and designs here",
        target: '_blank',
    },
    {
        id: 'book__python',
        name: 'Python Books',
        path: 'https://books.zuri.team/python-for-beginners?ref_id=DanielSwift',
        title: "Stuck in python? Purchase this book to help you understand the fundamentals of coding",
        target: '_blank',
    },
    {
        id: 'pitch',
        name: 'Background Check for Coders',
        path: 'https://background.zuri.team/',
        title: "Worried about who you're hiring? Leave that to us, we'll help screen the best for your organization!",
        target: '_blank',
    },
    {
        id: 'book__design',
        name: 'Design Books',
        path: 'https://books.zuri.team/design-rules',
        title: "Download the free books to take your design skills to a higher level",
        target: '_blank',
    },
    {
        id: 'contact',
        name: 'Contact Me',
        path: '/contact',
        title: "Want to connect?",
        target: '_blank',
    },
]